---
- hosts: localhost
  roles:
    - role: geerlingguy.drush
  tasks:
    - name: Ensure optional dependencies are installed
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - bzip2
        - bzr
        - gzip
        - subversion
        - unzip
        - mysql-server
        - php5-mysql

    - name: Installing zsh, vim, git, tmux, etc.
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
      - zsh
      - tmux
      - htop
      - tree

    - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
      shell: curl https://j.mp/spf13-vim3 -L -o - | sh


